let num1 = (Math.floor(Math.random()*2)+1);
let num2 = (Math.floor(Math.random()*2)+1);
let num3 = (Math.floor(Math.random()*2)+1);
let num4 = (Math.floor(Math.random()*2)+1);
let num5 = (Math.floor(Math.random()*2)+1);
let sum = num1+num2+num3+num4+num5;
let average = sum / 5;
console.log("Sum of 5 Random 2 Digit Numbers = "+sum);
console.log("Average of 5 Random 2 Digit Numbers = "+average);